[package]
name = "cedra-network-discovery"
description = "Cedra Network Peer Discovery"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-channels = { workspace = true }
cedra-config = { workspace = true }
cedra-crypto = { workspace = true }
cedra-event-notifications = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-network = { workspace = true }
cedra-rest-client = { workspace = true }
cedra-short-hex-str = { workspace = true }
cedra-time-service = { workspace = true }
cedra-types = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[dev-dependencies]
cedra-config = { workspace = true, features = ["testing"] }
cedra-netcore = { workspace = true, features = ["fuzzing"] }
cedra-temppath = { workspace = true }
rand = { workspace = true }
