[package]
name = "test_package"
version = "0.0.0"
upgrade_policy = "compatible"

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "mainnet" }

[addresses]
# change it to `source_addr = "_" when calling `create-resource-account-and-publish-package` from the cli
source_addr = "0xcafe"
