[package]
name = "Pyth"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-framework", rev = "mainnet" }

[addresses]
pyth = "_"
