[package]
name = "Marketplace"
version = "0.0.0"

[addresses]
marketplace = "_"

[dependencies]
AptosFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosToken = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-token", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-token-objects", rev = "mainnet" }