name: "Bump cedra-node cargo version"
description: |
  Bumps the cedra-node cargo version against the cedra-network branch name.
inputs:
  release_tag:
    description: "The release tag which includes the version to bump"
    required: true
  cedra_node_cargo_toml:
    description: "The path to the cedra-node Cargo.toml file"
    required: true

runs:
  using: composite
  steps:
    - name: Bump cedra-node-version
      shell: bash
      run: |
        python3 ${{ github.action_path }}/bump_cedra_node_version.py
      env:
        RELEASE_TAG: ${{ inputs.release_tag }}
        CEDRA_NODE_CARGO_TOML: ${{ inputs.cedra_node_cargo_toml }}
