[package]
name = 'tic-tac-toe'
version = '1.0.0'

[addresses]
tic_tac_toe = "_"

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "mainnet" }
