[package]
name = "fuzzer-fuzz"
version = "0.0.0"
publish = false
edition = "2021"
build = "build.rs"

[package.metadata]
cargo-fuzz = true

[dependencies]
cedra-cached-packages = { workspace = true }
cedra-consensus = { workspace = true, features = ["fuzzing"], optional = true }
cedra-crypto = { workspace = true }
cedra-framework = { workspace = true }
cedra-language-e2e-tests = { workspace = true, features = ["fuzzing"] }
cedra-transaction-simulation = { workspace = true }
cedra-types = { workspace = true, features = ["fuzzing"] }
cedra-vm = { workspace = true }
cedra-vm-environment = { workspace = true }
arbitrary = { workspace = true, features = ["derive"] }
base64 = { workspace = true }
bcs = { workspace = true }
libfuzzer-sys = "0.4"
move-binary-format = { workspace = true, features = ["fuzzing"] }
move-bytecode-verifier = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
move-vm-types = { workspace = true, features = ["fuzzing"] }
once_cell = { workspace = true }
rayon = { workspace = true }
ring = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
consensus = ["dep:cedra-consensus"]

[[bin]]
name = "move_value_deserialize"
path = "fuzz_targets/move/value_deserialize.rs"
test = false
doc = false

[[bin]]
name = "move_move_value_deserialize"
path = "fuzz_targets/move/move_value_deserialize.rs"
test = false
doc = false

[[bin]]
name = "move_move_value_decorate"
path = "fuzz_targets/move/move_value_decorate.rs"
test = false
doc = false

[[bin]]
name = "signed_transaction_deserialize"
path = "fuzz_targets/signed_transaction_deserialize.rs"
test = false
doc = false

[[bin]]
name = "move_cedravm_publish_and_run"
path = "fuzz_targets/move/cedravm_publish_and_run.rs"
test = false
doc = false

[[bin]]
name = "move_cedravm_publish"
path = "fuzz_targets/move/cedravm_publish.rs"
test = false
doc = false

[[bin]]
name = "move_cedravm_authenticators"
path = "fuzz_targets/move/cedravm_authenticators.rs"
test = false
doc = false

[[bin]]
name = "use_case_aware_shuffler"
path = "fuzz_targets/use_case_aware_shuffler.rs"
test = false
doc = false
required-features = ["consensus"]

[[bin]]
name = "deserialize_script_module"
path = "fuzz_targets/move/deserialize_script_module.rs"
test = false
doc = false

[[bin]]
name = "move_bytecode_verifier_compiled_modules"
path = "fuzz_targets/move/bytecode_verifier_compiled_modules.rs"
test = false
doc = false
