[package]
name = "cedra-db"
description = "Cedra database"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-accumulator = { workspace = true }
cedra-config = { workspace = true }
cedra-crypto = { workspace = true }
cedra-db-indexer = { workspace = true }
cedra-db-indexer-schemas = { workspace = true, features = ["fuzzing"] }
cedra-executor-types = { workspace = true }
cedra-experimental-runtimes = { workspace = true }
cedra-infallible = { workspace = true }
cedra-jellyfish-merkle = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-proptest-helpers = { workspace = true, optional = true }
cedra-resource-viewer = { workspace = true }
cedra-rocksdb-options = { workspace = true }
cedra-schemadb = { workspace = true }
cedra-scratchpad = { workspace = true }
cedra-storage-interface = { workspace = true, features = ["fuzzing"] }
cedra-temppath = { workspace = true, optional = true }
cedra-types = { workspace = true }
arc-swap = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
claims = { workspace = true }
clap = { workspace = true, optional = true }
crossbeam-channel = { workspace = true, optional = true }
dashmap = { workspace = true }
either = { workspace = true }
hex = { workspace = true }
indicatif = { workspace = true, optional = true }
itertools = { workspace = true }
lru = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
owo-colors = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rayon = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
status-line = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
cedra-executor-types = { workspace = true }
cedra-jellyfish-merkle = { workspace = true, features = ["fuzzing"] }
cedra-proptest-helpers = { workspace = true }
cedra-schemadb = { workspace = true, features = ["fuzzing"] }
cedra-scratchpad = { workspace = true, features = ["fuzzing"] }
cedra-temppath = { workspace = true }
cedra-types = { workspace = true }
ouroboros = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "cedra-proptest-helpers", "cedra-temppath", "cedra-crypto/fuzzing", "cedra-jellyfish-merkle/fuzzing", "cedra-types/fuzzing", "cedra-executor-types/fuzzing", "cedra-schemadb/fuzzing", "cedra-scratchpad/fuzzing"]
consensus-only-perf-test = []
db-debugger = ["cedra-temppath", "clap", "crossbeam-channel", "owo-colors", "indicatif"]
