[package]
name = "cedra-node-checker"
description = "Cedra Node Health Checker"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-config = { workspace = true }
cedra-crypto = { workspace = true }
cedra-logger = { workspace = true }
cedra-network-checker = { workspace = true }
cedra-rest-client = { workspace = true }
cedra-sdk = { workspace = true }
cedra-transaction-emitter-lib = { workspace = true }
cedra-transaction-workloads-lib = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
poem = { workspace = true }
poem-openapi = { workspace = true }
prometheus-parse = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[lib]
name = "cedra_node_checker_lib"
path = "src/lib.rs"
