[package]
name = "cedra-storage-service-server"
description = "The Cedra storage service (server-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-channels = { workspace = true }
cedra-config = { workspace = true }
cedra-infallible = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-network = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-storage-service-notifications = { workspace = true }
cedra-storage-service-types = { workspace = true }
cedra-time-service = { workspace = true }
cedra-types = { workspace = true }
arc-swap = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
mini-moka = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
cedra-bitvec = { workspace = true }
cedra-config = { workspace = true, features = ["fuzzing"] }
cedra-crypto = { workspace = true }
cedra-netcore = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-time-service = { workspace = true, features = ["async", "testing"] }
cedra-types = { workspace = true }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
