[package]
name = "cedra-whitelist"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
move-vm-runtime = { workspace = true }
anyhow.workspace = true
once_cell.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
url.workspace = true
cedra-sdk = { workspace = true }
hex.workspace = true


[lib]
path = "src/lib.rs"
