# :!:>manifest
[package]
name = 'UpgradeAndGovern'
version = '1.1.0'

[addresses]
upgrade_and_govern = '_'

[dependencies.AptosFramework]
git = "https://github.com/cedra-labs/cedra-framework.git"
subdir = "aptos-framework"
rev = "mainnet"