[package]
name = "cedra-experimental-bulk-txn-submit"
description = ""
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-config = { workspace = true }
cedra-logger = { workspace = true }
cedra-sdk = { workspace = true }
cedra-transaction-emitter-lib = { workspace = true }
cedra-transaction-generator-lib = { workspace = true }
bcs = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
