[package]
name = "hello_prover"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-framework/", rev = "main" }

[addresses]


