[package]
name = "cedra-storage-interface"
description = "Cedra storage interface"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-crypto = { workspace = true }
cedra-experimental-layered-map = { workspace = true }
cedra-infallible = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-scratchpad = { workspace = true }
cedra-secure-net = { workspace = true }
cedra-types = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cedra-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = ["cedra-types/fuzzing"]

[package.metadata.cargo-machete]
ignored = ["proptest"]
