[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"
aptos_framework = "0x1"

[dependencies]
AptosFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosToken = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-token", rev = "mainnet" }
