[package]
name = "Examples"
version = "0.0.0"

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "mainnet" }
CedraToken = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-token", rev = "mainnet" }

[addresses]
cedra_framework = "0x1"
# replace the admin_addr with the actual admin address we created using CLI
admin_addr = "0xbeef"