[package]
name = "cedra-db-tool"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-backup-cli = { workspace = true }
cedra-block-executor = { workspace = true }
cedra-config = { workspace = true }
cedra-db = { workspace = true, features = ["db-debugger"] }
cedra-db-indexer = { workspace = true }
cedra-executor = { workspace = true }
cedra-executor-types = { workspace = true }
cedra-logger = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-temppath = { workspace = true }
cedra-types = { workspace = true }
cedra-vm = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
cedra-backup-cli = { workspace = true, features = ["testing"] }
cedra-backup-service = { workspace = true }
cedra-executor-test-helpers = { workspace = true }
cedra-indexer-grpc-table-info = { workspace = true }
