# A simple composite action that checks if the calling repository is cedra-network
# There are some actions that should only be run on cedra-network, e.g. publishing or some expensive cron-jobs
inputs:
  cancel-workflow:
    description: "Cancel the workflow if the calling repository is not cedra-network"
    required: false
    default: false
  token:
    description: "The GitHub token to use"
    required: false
    default: ${{ github.token }}
outputs:
  is-cedra-network:
    description: "Whether the calling repository is cedra-network"
    value: ${{ steps.determine-repo.outputs.is-cedra-network }}
runs:
  using: composite
  steps:
    - name: Determine the calling repo
      id: determine-repo
      shell: bash
      run: |
        if [[ "${{ github.repository }}" == "cedra-labs/cedra-network" ]]; then
          echo "is-cedra-network=true" >> $GITHUB_OUTPUT
        else
          echo "is-cedra-network=false" >> $GITHUB_OUTPUT
        fi
        echo "Calling repo: ${{ github.repository }}"
    - name: Cancel the workflow if the calling repo is not cedra-network
      if: ${{ inputs.cancel-workflow == 'true' && steps.determine-repo.outputs.is-cedra-network == 'false' }}
      shell: bash
      run: |
        echo "Canceling workflow because the calling repo is not cedra-network"
        gh run cancel ${{ github.run_id }}
      env:
        GH_TOKEN: ${{ inputs.token }} # this is required for gh commands to work https://cli.github.com/manual/gh_help_environment
