[package]
name = "cedra-db-indexer-schemas"
description = "CedraDB Internal Indexer DB schemas"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-crypto = { workspace = true }
cedra-schemadb = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-types = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
serde = { workspace = true }

[dev-dependencies]
cedra-proptest-helpers = { workspace = true }
cedra-schemadb = { workspace = true, features = ["fuzzing"] }
cedra-types = { workspace = true, features = ["fuzzing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "cedra-types/fuzzing", "cedra-schemadb/fuzzing"]
