[package]
name = "CedraFramework"
version = "1.0.0"

[addresses]
std = "0x1"
cedra_std = "0x1"
cedra_framework = "0x1"
cedra_fungible_asset = "0xA"
cedra_token = "0x3"
core_resources = "0xA550C18"
vm_reserved = "0x0"
admin = "0x3c9124028c90111d7cfd47a28fae30612e397d115c7b78f69713fb729347a77e"

[dependencies]
CedraStdlib = { local = "../cedra-stdlib" }
MoveStdlib = { local = "../move-stdlib" }
