[package]
name = "cedra-transaction-workloads-lib"
description = "Library for Cedra transaction workloads"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cedra-framework = { workspace = true }
cedra-sdk = { workspace = true }
cedra-transaction-generator-lib = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
move-binary-format = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true }
