[package]
name = "cedra-transaction-generator-lib"
description = "Library for Cedra transaction generator"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-framework = { workspace = true }
cedra-infallible = { workspace = true }
cedra-logger = { workspace = true }
cedra-sdk = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
move-binary-format = { workspace = true }
move-package = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
