[package]
name = "CedraTokenObjects"
version = "1.0.0"

[addresses]
std = "0x1"
cedra_std = "0x1"
cedra_framework = "0x1"
cedra_token_objects = "0x4"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
CedraFramework = { local = "../cedra-framework"}
