[package]
name = "cedra-state-sync-driver"
description = "The driver for state sync"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-config = { workspace = true }
cedra-consensus-notifications = { workspace = true }
cedra-crypto = { workspace = true }
cedra-data-client = { workspace = true }
cedra-data-streaming-service = { workspace = true }
cedra-event-notifications = { workspace = true }
cedra-executor-types = { workspace = true }
cedra-infallible = { workspace = true }
cedra-logger = { workspace = true }
cedra-mempool-notifications = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-runtimes = { workspace = true }
cedra-schemadb = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-storage-service-notifications = { workspace = true }
cedra-time-service = { workspace = true }
cedra-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
cedra-channels = { workspace = true }
cedra-crypto = { workspace = true }
cedra-db = { workspace = true }
cedra-executor = { workspace = true }
cedra-executor-test-helpers = { workspace = true }
cedra-genesis = { workspace = true, features = ["testing"] }
cedra-network = { workspace = true }
cedra-storage-service-client = { workspace = true }
cedra-storage-service-types = { workspace = true }
cedra-temppath = { workspace = true }
cedra-time-service = { workspace = true, features = ["async", "testing"] }
cedra-vm = { workspace = true }
cedra-vm-genesis = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
mockall = { workspace = true }
move-core-types = { workspace = true }
ntest = { workspace = true }
rand = { workspace = true }
