[package]
name = "cedra-storage-service-client"
description = "The Cedra storage service (client-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cedra-config = { workspace = true }
cedra-network = { workspace = true }
cedra-storage-service-types = { workspace = true }
thiserror = { workspace = true }
