[package]
name = "BCSStream"
version = "0.0.0"

[addresses]
bcs_stream = "0xCAFE"

[dependencies]
CedraStdlib = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-stdlib", rev = "mainnet" }
