[package]
name = "cedra-executor-benchmark"
description = "Cedra executor benchmark"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-aggregator = { workspace = true }
cedra-block-executor = { workspace = true }
cedra-block-partitioner = { workspace = true }
cedra-config = { workspace = true }
cedra-crypto = { workspace = true }
cedra-db = { workspace = true }
cedra-executor = { workspace = true }
cedra-executor-service = { workspace = true }
cedra-executor-types = { workspace = true }
cedra-experimental-ptx-executor = { workspace = true }
cedra-experimental-runtimes = { workspace = true }
cedra-genesis = { workspace = true, features = ["testing"] }
cedra-jellyfish-merkle = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-mvhashmap = { workspace = true }
cedra-node-resource-metrics = { workspace = true }
cedra-push-metrics =  { workspace = true }
cedra-sdk = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-transaction-generator-lib = { workspace = true }
cedra-transaction-workloads-lib = { workspace = true }
cedra-types = { workspace = true }
cedra-vm = { workspace = true }
cedra-vm-environment = { workspace = true }
cedra-vm-logging = { workspace = true }
cedra-vm-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
move-core-types = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thread_local = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

[target.'cfg(unix)'.dependencies]
cedra-profiler = { workspace = true }
jemallocator = { version = "0.5.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }

[dev-dependencies]
cedra-temppath = { workspace = true }

[features]
default = []
fuzzing = ["cedra-config/fuzzing", "cedra-crypto/fuzzing", "cedra-types/fuzzing"]
