[package]
name = "cedra-testcases"
description = "Cedra compatibility tests"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra = { workspace = true, features = ["fuzzing"] }
cedra-config = { workspace = true }
cedra-forge = { workspace = true }
cedra-global-constants = { workspace = true }
cedra-keygen = { workspace = true }
cedra-logger = { workspace = true }
cedra-release-builder = { workspace = true }
cedra-rest-client = { workspace = true }
cedra-runtimes = { workspace = true }
cedra-sdk = { workspace = true }
cedra-temppath = { workspace = true }
cedra-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_approx_eq = { workspace = true }

[[test]]
name = "forge-local-compatibility"
harness = false

[[test]]
name = "forge-local-performance"
harness = false
