[package]
name = "cedra-scratchpad"
description = "Cedra scratchpad"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cedra-crypto = { workspace = true }
cedra-drop-helper = { workspace = true }
cedra-infallible = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-types = { workspace = true }
cedra-vm = { workspace = true }
bitvec = { workspace = true }
criterion = { workspace = true, optional = true }
dashmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true, optional = true }
rayon = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cedra-types = { workspace = true, features = ["fuzzing"] }
bitvec = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
jemallocator = { version = "0.5.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }

[features]
fuzzing = ["cedra-types/fuzzing", "proptest"]
bench = ["proptest", "criterion"]

[[bench]]
name = "sparse_merkle"
harness = false
required-features = ["bench"]

[lib]
# Allow Criterion benchmarks to take command line arguments
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false
