[package]
name = "ResourceGroupsSecondary"
version = "0.0.0"

[addresses]
resource_groups_primary = "_"
resource_groups_secondary = "_"

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "mainnet" }
ResourceGroupsPrimary = { local = "../primary" }
