[package]
name = "cedra-ledger"
description = "Library for integration with the Cedra app on Ledger"
version = "0.2.0"
publish = true

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = "https://github.com/cedra-labs/cedra-network/tree/main/crates/cedra-ledger"
rust-version = { workspace = true }

[dependencies]
cedra-crypto = { workspace = true }
cedra-types = { workspace = true }
hex = { workspace = true }
ledger-apdu = "0.10.0"
ledger-transport-hid = "0.10.0"
thiserror = { workspace = true }
