[package]
name = "cedra-db-indexer"
description = "CedraDB Internal Indexer"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-config = { workspace = true }
cedra-db-indexer-schemas = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-resource-viewer = { workspace = true }
cedra-rocksdb-options = { workspace = true }
cedra-schemadb = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
cedra-proptest-helpers = { workspace = true }
cedra-schemadb = { workspace = true, features = ["fuzzing"] }
cedra-types = { workspace = true, features = ["fuzzing"] }
rand = { workspace = true }

[features]
default = []
fuzzing = ["cedra-types/fuzzing", "cedra-schemadb/fuzzing"]
