name: Copy images to dockerhub on release
on:
  push:
    branches:
      # cedra-node network-specific release branches
      - devnet
      - testnet
      - mainnet
      # preview branches
      - preview
      - preview-networking
      # cedra-indexer-grpc network-specific release branches
      - cedra-indexer-grpc-devnet
      - cedra-indexer-grpc-testnet
      - cedra-indexer-grpc-mainnet
    tags:
      - cedra-node-v*
      - cedra-indexer-grpc-v*

permissions:
  contents: read
  id-token: write #required for GCP Workload Identity federation

jobs:
  copy-images-to-docker-hub:
    uses: ./.github/workflows/copy-images-to-dockerhub.yaml
    with:
      image_tag_prefix: ${{ github.ref_name }}
    secrets: inherit
