[package]
name = "ExperimentalUsecases"
version = "0.0.0"

[dependencies]
CedraFramework = { local = "../../../../../cedra-move/framework/cedra-framework" }
CedraExperimental = { local = "../../../../../cedra-move/framework/cedra-experimental" }
CedraToken = { local = "../../../../../cedra-move/framework/cedra-token" }
CedraTokenObjects = { local = "../../../../../cedra-move/framework/cedra-token-objects" }

# testing exchanging of constant address works as well.
[addresses]
publisher_address = "0xABCD"
