[package]
name = "cedra-backup-cli"
description = "Backup CLI"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-backup-service = { workspace = true }
cedra-config = { workspace = true }
cedra-crypto = { workspace = true }
cedra-db = { workspace = true }
cedra-db-indexer-schemas = { workspace = true }
cedra-executor = { workspace = true }
cedra-executor-test-helpers = { workspace = true }
cedra-executor-types = { workspace = true }
cedra-indexer-grpc-table-info = { workspace = true }
cedra-infallible = { workspace = true }
cedra-jellyfish-merkle = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-proptest-helpers = { workspace = true }
cedra-push-metrics = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-temppath = { workspace = true }
cedra-types = { workspace = true }
cedra-vm = { workspace = true }
cedra-vm-environment = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-io-timeout = { workspace = true }
tokio-stream = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true }

[dev-dependencies]
cedra-backup-service = { workspace = true }
cedra-config = { workspace = true }
cedra-db = { workspace = true }
cedra-executor-test-helpers = { workspace = true }
cedra-proptest-helpers = { workspace = true }
cedra-storage-interface = { workspace = true }
proptest = { workspace = true }
warp = { workspace = true }

[features]
testing = []
fuzzing = ["cedra-db/fuzzing"]
