[package]
name = "TooLargeTest"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-framework", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "move-stdlib", rev = "mainnet" }
