[package]
name = 'knight'
version = '1.0.0'

[addresses]
knight = "_"

[dependencies]
AptosFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-token-objects", rev = "mainnet" }
