[package]
name = "cedra-executor"
description = "Cedra executor"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-block-executor = { workspace = true }
cedra-consensus-types = { workspace = true }
cedra-crypto = { workspace = true }
cedra-drop-helper = { workspace = true }
cedra-executor-service = { workspace = true }
cedra-executor-types = { workspace = true }
cedra-experimental-runtimes = { workspace = true }
cedra-indexer-grpc-table-info = { workspace = true }
cedra-infallible = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-sdk = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-types = { workspace = true }
cedra-vm = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
fail = { workspace = true }
itertools = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
cedra-cached-packages = { workspace = true }
cedra-config = { workspace = true }
cedra-db = { workspace = true }
cedra-db-indexer = { workspace = true, features = ["fuzzing"] }
cedra-executor-test-helpers = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-temppath = { workspace = true }
cedra-transaction-simulation = { workspace = true }
cedra-types = { workspace = true, features = ["testing"] }
cedra-vm-genesis = { workspace = true }
arr_macro = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["cedra-consensus-types/fuzzing", "cedra-crypto/fuzzing", "cedra-types/fuzzing", "cedra-storage-interface/fuzzing"]
failpoints = ["fail/failpoints", "cedra-vm/failpoints"]
consensus-only-perf-test = []

[[bench]]
name = "data_collection"
harness = false
