{
 "title": "ddos",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "network_id", "query": { "query": "label_values(network_id)" } },
   { "name": "role_type", "query": { "query": "label_values(role_type)" } },
   { "name": "rpc_protocol", "label": "RPC Protocol", "query": { "query": "label_values(protocol_id)" } },
   { "name": "AggInterval", "label": "Aggregation Interval", "query": "1m,5m,15m,30m,1h,3h,1d,7d" },
   { "name": "container", "query": { "query": "label_values(container)" } }
  ]
 },
 "panels": [
  {
   "title": "Inbound Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Connected Peers",
   "type": "graph",
   "description": "Total Inbound connected peers.  There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (role_type, network_id) (cedra_connections{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", direction=\"inbound\"})",
     "legendFormat": "{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Inbound Pending Connection Upgrades",
   "type": "graph",
   "description": "The rate of new inbound connections on the network interface",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (role_type, network_id) (rate(cedra_network_pending_connection_upgrades{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", direction=\"inbound\" }[$AggInterval]))",
     "legendFormat": "{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Blocked Inbound Connections Rate (Connection Limit)",
   "type": "graph",
   "description": "Rate of connections being blocked by connection limits",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cedra_connections_rejected{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", direction=\"inbound\"}[1m])",
     "legendFormat": "{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Throughput of Total Inbound RPCs (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Inbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (role_type, network_id)(rate(cedra_network_rpc_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Rate of Total Inbound RPCs (msg/s)",
   "type": "graph",
   "description": "Total number of all Inbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (role_type, network_id)(rate(cedra_network_rpc_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", type=\"request\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Throughput of Total Inbound Direct Sends (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Inbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (role_type, network_id)(rate(cedra_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Rate of Total Inbound Direct Sends (msg/s)",
   "type": "graph",
   "description": "Total number of all Inbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (role_type, network_id)(rate(cedra_network_direct_send_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "VFN Public Inbound Allowed bytes (bytes/s)",
   "type": "graph",
   "description": "number of bytes allowed through the throttler inbound per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(cedra_network_rate_limit_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", metric=\"allowed\", direction=\"inbound\"}[$AggInterval])"
    }
   ]
  },
  {
   "title": "VFN Public Inbound Rate Limiting (bytes/s)",
   "type": "graph",
   "description": "number of bytes throttled inbound per second including partial messages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(cedra_network_rate_limit_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", metric=\"throttled\", direction=\"inbound\"}[$AggInterval])"
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage - $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "repeat": "container",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{container=~\"$container\"}[$AggInterval]))",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{container_name=~\"$container\"}[$AggInterval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "IO Operations - $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 146 },
   "repeat": "container",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{container=~\"$container\"}[$AggInterval])",
     "legendFormat": "{{container}}-reads"
    },
    {
     "expr": "rate(container_fs_writes_total{container=~\"$container\"}[$AggInterval])",
     "legendFormat": "{{container}}-writes"
    },
    {
     "expr": "rate(container_fs_reads_total{container_name=~\"$container\"}[$AggInterval]) ",
     "legendFormat": "{{container_name}}-reads"
    },
    {
     "expr": "rate(container_fs_writes_total{container_name=~\"$container\"}[$AggInterval])",
     "legendFormat": "{{container_name}}-writes"
    }
   ]
  },
  {
   "title": "Memory Usage % - $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 258 },
   "repeat": "container",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=~\"$container\"} / container_spec_memory_limit_bytes{container=~\"$container\"}",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container_name=~\"$container\"} / container_spec_memory_limit_bytes{container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage % -$container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 370 },
   "repeat": "container",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*-($container)-e.*\"} / kubelet_volume_stats_capacity_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*-($container)-e.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}