{
 "title": "transactions",
 "tags": [ "cedra-core" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "BigQuery", "query": "grafana-bigquery-datasource" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "label": "Aggregation Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Committed successful txns per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(0.5, rate(cedra_consensus_last_committed_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]))",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Transactions by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (state) (0.5, sum by (state, kubernetes_pod_name) (rate(cedra_processed_txns_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", state!=\"success\"}[$interval])))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Transactions by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (kind) (0.5, sum by (kind, kubernetes_pod_name) (rate(cedra_processed_txns_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", state!=\"success\"}[$interval])))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Ecosystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Function transactions by user module",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (account, name) (0.5, sum by (kubernetes_pod_name, account, name) (rate(cedra_processed_user_transactions_entry_function_by_module{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"true\", account!=\"core\"}[$interval])))\n\n\n",
     "legendFormat": "{{account}}-{{name}}"
    }
   ]
  },
  {
   "title": "Failed function transactions by module",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (account, name, state) (0.5, sum by (kubernetes_pod_name, account, name, state) (rate(cedra_processed_user_transactions_entry_function_by_module{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"true\", state!=\"keep_success\"}[$interval])))\n",
     "legendFormat": "{{account}}-{{name}}-{{state}}"
    }
   ]
  },
  {
   "title": "User methods by failure rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "connectionArgs": { "location": "US" },
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "SELECT 100 * (failed_count / total_count) as failure_percent, failed_count, total_count, SPLIT(fun, \"::\")[OFFSET(1)] as module, SPLIT(fun, \"::\")[OFFSET(2)] as method\nFROM (\n  SELECT fun, SUM(failed_count) as failed_count, ARRAY_AGG((vm_status, failed_count)) AS vm_statuses\n  FROM (\n    SELECT \n      JSON_EXTRACT_SCALAR(json_payload, \"$.function\") as fun, \n      vm_status,\n      SUM(1) as failed_count\n    FROM `analytics-test-345723.indexer_mainnet_gcp.transactions_view` \n    WHERE success=false and $__timeFilter(inserted_at)\n    GROUP BY fun, vm_status\n  ) z\n  WHERE NOT(fun LIKE \"0x1::%\") AND NOT(fun LIKE \"0x3::%\")\n  GROUP BY fun\n) a\nJOIN (\n  SELECT entry_function_id_str, SUM(1) as total_count\n  FROM `analytics-test-345723.indexer_mainnet_gcp.user_transactions`\n  where $__timeFilter(timestamp)\n  GROUP BY entry_function_id_str\n) b\nON fun = entry_function_id_str\nORDER BY total_count DESC, failed_count DESC\nLIMIT 30\n"
    }
   ]
  },
  {
   "title": "Ecosystem (non 0x1) function failure rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile (0.5, sum by (kubernetes_pod_name) (rate(cedra_processed_user_transactions_entry_function_by_module{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"true\", state!=\"keep_success\", account=\"user\"}[$interval]))) / quantile (0.5, sum by (kubernetes_pod_name) (rate(cedra_processed_user_transactions_entry_function_by_module{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"true\", account=\"user\"}[$interval])))\n",
     "legendFormat": "{{account}}-{{name}}-{{state}}"
    }
   ]
  },
  {
   "title": "Failure rate by module (with >0.1 TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "((quantile by (account, name) (0.5, sum by (kubernetes_pod_name, account, name) (rate(cedra_processed_user_transactions_entry_function_by_module{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"true\", state!=\"keep_success\"}[$interval]))) > 0.1) / quantile by (account, name) (0.5, sum by (kubernetes_pod_name, account, name) (rate(cedra_processed_user_transactions_entry_function_by_module{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"true\"}[$interval])))) < 1.1\n",
     "legendFormat": "{{account}}-{{name}}-{{state}}"
    }
   ]
  },
  {
   "title": "User methods by failure code",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "connectionArgs": { "location": "US" },
     "location": "US",
     "project": "analytics-test-345723",
     "rawSql": "SELECT 100 * (failed_count / total_count) as failure_percent, failed_count, SPLIT(fun, \"::\")[OFFSET(1)] as module, SPLIT(fun, \"::\")[OFFSET(2)] as method, vm_status\nFROM (\n  SELECT \n    JSON_EXTRACT_SCALAR(json_payload, \"$.function\") as fun, \n    vm_status,\n    SUM(1) as failed_count\n  FROM `analytics-test-345723.indexer_mainnet_gcp.transactions_view` \n  WHERE success=false and $__timeFilter(inserted_at) AND NOT(JSON_EXTRACT_SCALAR(json_payload, \"$.function\") LIKE \"0x1::%\") AND NOT(JSON_EXTRACT_SCALAR(json_payload, \"$.function\") LIKE \"0x3::%\")\n  GROUP BY fun, vm_status\n\n) a\nJOIN (\n  SELECT entry_function_id_str, SUM(1) as total_count\n  FROM `analytics-test-345723.indexer_mainnet_gcp.user_transactions`\n  where $__timeFilter(timestamp)\n  GROUP BY entry_function_id_str\n) b\nON fun = entry_function_id_str\nORDER BY failed_count DESC\nLIMIT 30\n\n"
    }
   ]
  },
  { "title": "Failures Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Failed reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (state, reason) (0.5, sum by (kubernetes_pod_name, state, reason) (rate(cedra_processed_failed_txns_reason_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"false\"}[$interval])))",
     "legendFormat": "{{state}}-{{reason}}"
    }
   ]
  },
  {
   "title": "Detailed failed reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (state, reason, error_code) (0.5, sum by (state, reason, error_code, kubernetes_pod_name) (rate(cedra_processed_failed_txns_reason_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"true\"}[$interval])))",
     "legendFormat": "{{state}}-{{reason}}-{{error_code}}"
    }
   ]
  },
  {
   "title": "Core function failures by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (module, method) (0.5, sum by (kubernetes_pod_name, module, method) (rate(cedra_processed_user_transactions_entry_function_by_core_method{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", state!=\"keep_success\"}[$interval])))\n\n",
     "legendFormat": "{{module}}-{{method}}"
    }
   ]
  },
  { "title": "User transaction breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "User transactions by payload type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (payload_type) (0.5, sum by (kubernetes_pod_name, payload_type) (rate(cedra_processed_user_transactions_by_payload{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", state!=\"\"}[$interval])))",
     "legendFormat": "{{payload_type}}"
    }
   ]
  },
  {
   "title": "Function transactions status by module",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (account, state) (0.5, sum by (account, state) (rate(cedra_processed_user_transactions_entry_function_by_module{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"false\"}[$interval])))\n\n\n",
     "legendFormat": "{{account}}-{{state}}"
    }
   ]
  },
  {
   "title": "Function transactions by module",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (account, name) (0.5, sum by (kubernetes_pod_name, account, name) (rate(cedra_processed_user_transactions_entry_function_by_module{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"true\"}[$interval])))\n\n\n",
     "legendFormat": "{{account}}-{{name}}"
    }
   ]
  },
  {
   "title": "Core function transactions by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (module, method) (0.5, sum by (kubernetes_pod_name, module, method) (rate(cedra_processed_user_transactions_entry_function_by_core_method{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])))\n\n",
     "legendFormat": "{{module}}-{{method}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Emitted events by account of the module",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (process, account, creation_number) (0.5, rate(cedra_processed_user_transactions_core_events{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"false\"}[$interval]))>0\n\n\n",
     "legendFormat": "{{process}}-{{account}}-{{creation_number}}"
    }
   ]
  },
  {
   "title": "Emitted events by account of the module",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile by (account, creation_number) (0.5, sum by (kubernetes_pod_name, account, creation_number) (rate(cedra_processed_user_transactions_core_events{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", is_detailed=\"true\"}[$interval])))\n\n\n",
     "legendFormat": "{{account}}-{{creation_number}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Avg Txn Total Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(cedra_vm_txn_total_seconds_sum{kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(cedra_vm_txn_total_seconds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg Txn Validation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(cedra_vm_txn_validation_seconds_sum{kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])/rate(cedra_vm_txn_validation_seconds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg Time per Gas Unit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "s", "label": "seconds / unit gas" }
   ],
   "targets": [
    {
     "expr": "rate(cedra_vm_txn_total_seconds_sum{kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])/rate(cedra_vm_txn_total_seconds_count{kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])/(rate(cedra_vm_txn_gas_usage_sum{kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])/rate(cedra_vm_txn_gas_usage_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  { "title": "Gas Market", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Avg Gas per User Txn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none", "label": "gas/txn" }
   ],
   "targets": [
    {
     "expr": "sum by (role) (rate(cedra_vm_txn_gas_usage_sum{kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) / sum by (role) (rate(cedra_vm_txn_gas_usage_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Inserted transactions by gas price bucket",
   "type": "timeseries",
   "description": "Rate of inserted transactions per ranking score bucket",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (role, bucket) (rate(cedra_core_mempool_txn_ranking_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"insert\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions pulled by gas price bucket",
   "type": "timeseries",
   "description": "Rate of consensus pulled transactions per ranking score bucket",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (role, bucket) (rate(cedra_core_mempool_txn_ranking_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"consensus_pulled\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}