[package]
name = "cedra-language-e2e-tests"
description = "Move language e2e testing framework"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-abstract-gas-usage = { workspace = true }
cedra-bitvec = { workspace = true }
cedra-block-executor = { workspace = true }
cedra-cached-packages ={ workspace = true }
cedra-crypto = { workspace = true, features = ["fuzzing"] }
cedra-framework = { workspace = true }
cedra-gas-algebra = { workspace = true }
cedra-gas-meter = { workspace = true }
cedra-gas-profiling = { workspace = true }
cedra-gas-schedule = { workspace = true }
cedra-keygen = { workspace = true }
cedra-proptest-helpers = { workspace = true }
cedra-rest-client = { workspace = true }
cedra-temppath = { workspace = true }
cedra-transaction-simulation = { workspace = true }
cedra-types = { workspace = true }
cedra-validator-interface = { workspace = true }
cedra-vm = { workspace = true }
cedra-vm-environment = { workspace = true }
cedra-vm-genesis = { workspace = true }
cedra-vm-logging = { workspace = true }
cedra-vm-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
goldenfile = { workspace = true }
move-binary-format = { workspace = true }
move-command-line-common = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
move-ir-compiler = { workspace = true }
move-model = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
petgraph = "0.5.1"
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[features]
default = []
fuzzing = []
