[package]
name = "ManagedFungibleToken"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
example_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-framework", rev = "mainnet" }
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
