[package]
name = "cedra-data-client"
description = "The Cedra data client"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cedra-config = { workspace = true }
cedra-crypto = { workspace = true }
cedra-id-generator = { workspace = true }
cedra-infallible = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-netcore = { workspace = true }
cedra-network = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-storage-service-client = { workspace = true }
cedra-storage-service-types = { workspace = true }
cedra-time-service = { workspace = true }
cedra-types = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
maplit = { workspace = true }
ordered-float = { workspace = true }
# Note: we cannot rely on the workspace version of rand because it's out-of-date
# and does not provide the necessary interfaces for weighted sampling. Similarly,
# it's not trivial to update rand on the workspace because of several dependency
# issues (e.g., other outdated crate versions). This is why we fix the version here.
# Eventually we'll need to update the workspace to use the latest version of rand.
# See also https://github.com/cedra-labs/cedra-network/issues/13031
rand = "0.8.5"
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
cedra-channels = { workspace = true }
cedra-network = { workspace = true, features = ["fuzzing"] }
cedra-peer-monitoring-service-types = { workspace = true }
cedra-storage-service-server = { workspace = true }
cedra-time-service = { workspace = true, features = ["async", "testing"] }
async-trait = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
tokio = { workspace = true }
