[package]
name = "cedra-backup-service"
description = "Backup service"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cedra-crypto = { workspace = true }
cedra-db = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-runtimes = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
hyper = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
warp = { workspace = true }

[dev-dependencies]
cedra-config = { workspace = true }
cedra-db = { workspace = true, features = ["fuzzing"] }
cedra-temppath = { workspace = true }
reqwest = { workspace = true }

[features]
fuzzing = ["cedra-db/fuzzing"]
