[package]
name = "cedra-debugger"
version = "0.1.0"
description = "Debugging tools."

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-consensus = { workspace = true }
cedra-db-tool = { workspace = true }
cedra-logger = { workspace = true }
cedra-move-debugger = { workspace = true }
cedra-push-metrics = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { version = "0.5.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }
