[package]
name = "cedra-safety-rules"
description = "Cedra safety rules"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cedra-config = { workspace = true }
cedra-consensus-types = { workspace = true }
cedra-crypto = { workspace = true }
cedra-global-constants = { workspace = true }
cedra-infallible = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-secure-net = { workspace = true }
cedra-secure-storage = { workspace = true }
cedra-types = { workspace = true }
cedra-vault-client = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true, optional = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cedra-config = { workspace = true, features = ["fuzzing"] }
cedra-consensus-types = { workspace = true, features = ["fuzzing"] }
cedra-proptest-helpers = { workspace = true }
cedra-secure-storage = { workspace = true, features = ["testing"] }
claims = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
rusty-fork = { workspace = true }
tempfile = { workspace = true }

[[bench]]
name = "safety_rules"
harness = false
required-features = ["testing"]

[features]
default = []
fuzzing = ["cedra-consensus-types/fuzzing", "cedra-config/fuzzing", "proptest"]
testing = ["cedra-secure-storage/testing"]
