[package]
name = "Examples"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"

[dependencies]
AptosFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "aptos-framework", rev = "mainnet" }
