[package]
name = "cedra-indexer-grpc-fullnode"
description = "Cedra Indexer GRPC runtime on fullnode."
version = "1.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }

cedra-api = { workspace = true }
cedra-api-types = { workspace = true }
cedra-bitvec = { workspace = true }
cedra-config = { workspace = true }
cedra-indexer-grpc-utils = { workspace = true }
cedra-logger = { workspace = true }
cedra-mempool = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-moving-average = { workspace = true }
cedra-protos = { workspace = true }
cedra-runtimes = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-types = { workspace = true }

move-core-types = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }

cedra-api-test-context = { workspace = true }
cedra-crypto = { workspace = true }
cedra-db = { workspace = true }
cedra-executor = { workspace = true }
cedra-executor-types = { workspace = true }
cedra-framework = { workspace = true }
cedra-genesis = { workspace = true }
cedra-global-constants = { workspace = true }
cedra-mempool = { workspace = true }
cedra-mempool-notifications = { workspace = true }
cedra-proptest-helpers = { workspace = true }
cedra-sdk = { workspace = true }
cedra-secure-storage = { workspace = true }
cedra-temppath = { workspace = true }
cedra-vm = { workspace = true }
cedra-vm-validator = { workspace = true }
