# :!:>manifest
[package]
name = 'UpgradeAndGovern'
version = '1.0.0'

[addresses]
upgrade_and_govern = '_'

[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-framework.git"
subdir = "cedra-framework"
rev = "mainnet"