[package]
name = "cedra-executor-service"
description = "Cedra executor service"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cedra-block-executor = { workspace = true }
cedra-block-partitioner = { workspace = true }
cedra-config = { workspace = true }
cedra-infallible = { workspace = true }
cedra-keygen = { workspace = true }
cedra-language-e2e-tests = { workspace = true }
cedra-logger = { workspace = true }
cedra-metrics-core = { workspace = true }
cedra-node-resource-metrics = { workspace = true }
cedra-push-metrics =  { workspace = true }
cedra-secure-net = { workspace = true }
cedra-storage-interface = { workspace = true }
cedra-transaction-simulation = { workspace = true }
cedra-types = { workspace = true }
cedra-vm = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
ctrlc = "3.4.0"
dashmap = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cedra-language-e2e-tests = { workspace = true }
cedra-vm = { workspace = true }
