[package]
name = "cedra-faucet-service"
description = "Cedra Faucet Service"
version = "2.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cedra-faucet-core = { workspace = true }
cedra-logger = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
